<?php 
    $_personalizationHelper = $this->helper('printscience_personalization/output');
    $_product = $this->getProduct(); 
?>
<?php if ($_personalizationHelper->isPersonalizationEnabled($_product)): ?>
    <?php $buttonTitle = $this->__('Personalize'); ?>
<?php else: ?>
    <?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php endif; ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>